name: Sonar-cloud
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
   name: Sonar-cloud Trigger
   runs-on: ubuntu-latest
   steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Analyze with Sonarcloud
      uses: sonarsource/sonarcloud-github-action@v1.3
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       
